### ISSUE TITLE
Error creating server, user_data property must be base64 encoded value

### ISSUE THREAD

**Issue by littleblackcloud** [cherryservers/terraform-provider-cherryservers#26]
Creating a server with `user_data` fails with the error message:

```
│ Error: error creating server, user_data property must be base64 encoded value
│ 
│   with cherryservers_server.test,
│   on main.tf line 29, in resource "cherryservers_server" "test":
│   29: resource "cherryservers_server" "test" {
│ 
```

Here's the terraform `main.tf` file:

```
terraform {
  required_providers {
    cherryservers = {
      source  = "cherryservers/cherryservers"
      version = "~> 0.0.6"
    }
  }

  required_version = ">= 1.9.4"
}

variable "cherry_api_token" {}

provider "cherryservers" {
  api_token = var.cherry_api_token 
}

resource "cherryservers_server" "test" {
  plan       = "cloud_vps_1"
  hostname   = "test"
  project_id = xxxxxx
  region     = "eu_nord_1"
  image      = "debian_12_64bit"
  user_data     = filebase64("${path.module}/cloud-init.yaml")
}

output "server_test_ip_addresses" {
  value = cherryservers_server.test.ip_addresses
}
```

Here's the `cloud-init.yaml` file:

```
#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

users:
  - name: test
    groups: users
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-ed25519 xxxxxxxxxxxxx

timezone: UTC

packages:
  - jq
```

Not sure why it's complaining that the `cloud-init.yaml` isn't base64 encoded when `terraform apply` shows that it is.
